backend:
  name: github
  repo: Applehand/eleventy-site
  branch: master
  auth_endpoint: https://auth.applehand.dev/auth

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "essays"
    label: "Essays"
    folder: "library/essays"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "technical-writings"
    label: "Technical Writings"
    folder: "library/technical-writings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "thoughts"
    label: "Thoughts"
    folder: "library/thoughts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "creative"
    label: "Creative Writings"
    folder: "library/creative"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
